In [1]:
import pandas as pd

In [6]:
df1 = pd.read_parquet('data/data_cb_merge.parquet')
df1

,user_id,location,name_hotel,descriptions
0,1,Da Lat,"Anh Quan Khoi Hotel,Minh Chien Hotel,9Trip Sta...",Comfortable Accommodations: Anh Quan Khoi Hote...
1,1,Danang,"Century Hotel Da Nang,Mộc Nhiên Hotel Da Nang,...",Comfortable Accommodations: Century Hotel Da N...
2,1,Hanoi,"Casa Valentina Hanoi Hotel,Mövenpick Living We...",Comfortable Accommodations: Casa Valentina Han...
3,1,Ho Chi Minh City,"Sheraton Saigon Grand Opera Hotel,Spacious 4BR...",Prime City Center Location: Sheraton Saigon Gr...
4,1,Hoi An,Grand Sunrise Palace Hoi An- A Luxury Indochin...,Elegant Accommodations: Grand Sunrise Palace H...
...,...,...,...,...
18500,41191,Danang,"Waikiki Beach Hotel Da Nang,Tashi Oasis Hotel ...",Beachfront Location: Waikiki Beach Hotel Da Na...
18501,42080,Hanoi,"Minerva Premium Hotel,La Siesta Premium Lakesi...",Comfortable Accommodations: Minerva Premium Ho...
18502,42328,Hoi An,"The Sun Homestay,iHome Hoi An,Cam Nam Homestay...",Prime Location: The Sun Homestay in Hoi An off...
18503,54611,Hanoi,"Myrcella Urban Apartment,Label6 To Ngoc Van - ...",Comfortable Accommodations: Myrcella Urban Apa...
18504,61506,Danang,"White Sand Boutique Hotel,HH Residence - Servi...",Comfortable Accommodations: White Sand Boutiqu...

In [22]:
df1.columns = df1.columns.str.lower()
df1 = df1.rename(columns={"userid": "user_id"})

In [23]:
df1

,user_id,location,name hotel,descriptions
0,1,Da Lat,"Anh Quan Khoi Hotel,Minh Chien Hotel,9Trip Sta...",Comfortable Accommodations: Anh Quan Khoi Hote...
1,1,Danang,"Century Hotel Da Nang,Mộc Nhiên Hotel Da Nang,...",Comfortable Accommodations: Century Hotel Da N...
2,1,Hanoi,"Casa Valentina Hanoi Hotel,Mövenpick Living We...",Comfortable Accommodations: Casa Valentina Han...
3,1,Ho Chi Minh City,"Sheraton Saigon Grand Opera Hotel,Spacious 4BR...",Prime City Center Location: Sheraton Saigon Gr...
4,1,Hoi An,Grand Sunrise Palace Hoi An- A Luxury Indochin...,Elegant Accommodations: Grand Sunrise Palace H...
...,...,...,...,...
18500,41191,Danang,"Waikiki Beach Hotel Da Nang,Tashi Oasis Hotel ...",Beachfront Location: Waikiki Beach Hotel Da Na...
18501,42080,Hanoi,"Minerva Premium Hotel,La Siesta Premium Lakesi...",Comfortable Accommodations: Minerva Premium Ho...
18502,42328,Hoi An,"The Sun Homestay,iHome Hoi An,Cam Nam Homestay...",Prime Location: The Sun Homestay in Hoi An off...
18503,54611,Hanoi,"Myrcella Urban Apartment,Label6 To Ngoc Van - ...",Comfortable Accommodations: Myrcella Urban Apa...
18504,61506,Danang,"White Sand Boutique Hotel,HH Residence - Servi...",Comfortable Accommodations: White Sand Boutiqu...

In [24]:
df1 = df1.rename(columns={"name hotel": "name_hotel"})

In [25]:
df1

,user_id,location,name_hotel,descriptions
0,1,Da Lat,"Anh Quan Khoi Hotel,Minh Chien Hotel,9Trip Sta...",Comfortable Accommodations: Anh Quan Khoi Hote...
1,1,Danang,"Century Hotel Da Nang,Mộc Nhiên Hotel Da Nang,...",Comfortable Accommodations: Century Hotel Da N...
2,1,Hanoi,"Casa Valentina Hanoi Hotel,Mövenpick Living We...",Comfortable Accommodations: Casa Valentina Han...
3,1,Ho Chi Minh City,"Sheraton Saigon Grand Opera Hotel,Spacious 4BR...",Prime City Center Location: Sheraton Saigon Gr...
4,1,Hoi An,Grand Sunrise Palace Hoi An- A Luxury Indochin...,Elegant Accommodations: Grand Sunrise Palace H...
...,...,...,...,...
18500,41191,Danang,"Waikiki Beach Hotel Da Nang,Tashi Oasis Hotel ...",Beachfront Location: Waikiki Beach Hotel Da Na...
18501,42080,Hanoi,"Minerva Premium Hotel,La Siesta Premium Lakesi...",Comfortable Accommodations: Minerva Premium Ho...
18502,42328,Hoi An,"The Sun Homestay,iHome Hoi An,Cam Nam Homestay...",Prime Location: The Sun Homestay in Hoi An off...
18503,54611,Hanoi,"Myrcella Urban Apartment,Label6 To Ngoc Van - ...",Comfortable Accommodations: Myrcella Urban Apa...
18504,61506,Danang,"White Sand Boutique Hotel,HH Residence - Servi...",Comfortable Accommodations: White Sand Boutiqu...

In [26]:
df1.to_parquet('data/data_cb_merge.parquet')

In [7]:
df1[df1['UserID'] == 1]

,UserID,Location,Name Hotel,Descriptions
0,1,Da Lat,"Anh Quan Khoi Hotel,Minh Chien Hotel,9Trip Sta...",Comfortable Accommodations: Anh Quan Khoi Hote...
1,1,Danang,"Century Hotel Da Nang,Mộc Nhiên Hotel Da Nang,...",Comfortable Accommodations: Century Hotel Da N...
2,1,Hanoi,"Casa Valentina Hanoi Hotel,Mövenpick Living We...",Comfortable Accommodations: Casa Valentina Han...
3,1,Ho Chi Minh City,"Sheraton Saigon Grand Opera Hotel,Spacious 4BR...",Prime City Center Location: Sheraton Saigon Gr...
4,1,Hoi An,Grand Sunrise Palace Hoi An- A Luxury Indochin...,Elegant Accommodations: Grand Sunrise Palace H...
5,1,Hue,"Hue Sweethouse 1 Homestay,Pilgrimage Village B...",Comfortable Accommodations: Hue Sweethouse 1 H...
6,1,Nha Trang,"Holiday Central Nha Trang,PANORAMA Condotel by...",Comfortable Accommodations: Holiday Central Nh...
7,1,Ninh Binh,"Wyndham Grand Vedana Ninh Binh Resort,Tam Coc ...",Elegant Accommodations: Wyndham Grand Vedana N...
8,1,Phú Quốc,"SOL by Meliá Phu Quoc,Mövenpick Villas & Resid...","Boasting a private beach area in Duong To, SOL..."

In [2]:
df2 = pd.read_parquet('data/data_merge.parquet')
df2

,hotel_id,user_id,user,country,review,rating,hotel_url,hotel_location,hotel_name,hotel_description,hotel_address,hotel_avg_rating
0,2,3,Lê,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-2-phon...,Vung Tau,Căn hộ 2 Phòng ngủ Tháp Tam Thắng,Beachfront Location: Căn hộ 2 Phòng ngủ Tháp T...,"Lihi Homestay, 790900 Vung Tau, Vietnam",9.25
1,2,17,Bánh,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-2-phon...,Vung Tau,Căn hộ 2 Phòng ngủ Tháp Tam Thắng,Beachfront Location: Căn hộ 2 Phòng ngủ Tháp T...,"Lihi Homestay, 790900 Vung Tau, Vietnam",9.25
2,2,6,Kỳ,Vietnam,Ổn nếu biết cách khắc phục.,7.0,https://www.booking.com/hotel/vn/can-ho-2-phon...,Vung Tau,Căn hộ 2 Phòng ngủ Tháp Tam Thắng,Beachfront Location: Căn hộ 2 Phòng ngủ Tháp T...,"Lihi Homestay, 790900 Vung Tau, Vietnam",9.25
3,2,15,Ngọc,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-2-phon...,Vung Tau,Căn hộ 2 Phòng ngủ Tháp Tam Thắng,Beachfront Location: Căn hộ 2 Phòng ngủ Tháp T...,"Lihi Homestay, 790900 Vung Tau, Vietnam",9.25
4,3,7,Công,Vietnam,Ok,9.0,https://www.booking.com/hotel/vn/khach-san-lam...,Hanoi,Lam Anh Hotel 8 Ngoại Giao Đoàn BT3-10,Comfortable Accommodations: Lam Anh Hotel 8 Ng...,"BT3-10, Khu biệt thự, khu đoàn ngoại giao, phư...",9.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1474574,8165,216,Diego,Brazil,Very Good,8.0,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63
1474575,8165,333,Martina,Italy,Very Good,8.0,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63
1474576,8165,75577,Reynald,France,Very Good,8.0,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63
1474577,8165,131478,Ivarsson,Sweden,Very Good,8.0,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63
1474578,8165,986,Osvaldo,France,Very Good,8.0,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63

In [3]:
df2[df2['hotel_id']==7]

,hotel_id,user_id,user,country,review,rating,hotel_url,hotel_location,hotel_name,hotel_description,hotel_address,hotel_avg_rating
245,7,741,Tú,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
246,7,686,Phát,Vietnam,"Rất dễ chịu, giá cả phải chăng. Sẽ quay lại.",9.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
247,7,138,Nguyen,Vietnam,Wonderful,9.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
248,7,813,Trần,Vietnam,Wonderful,9.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
249,7,3093,Sakura,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
250,7,338,Mai,Vietnam,Tuyệt vời ạ,10.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
251,7,4737,Naveen,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
252,7,523,Xuân,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
253,7,124,Trang,Vietnam,Wonderful,9.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
254,7,4008,Kien,Vietnam,Very Good,8.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
255,7,4468,Ánh,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
256,7,2417,360,Vietnam,Very Good,8.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
257,7,358,An,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
258,7,2865,Daiichi,Vietnam,Wonderful,9.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
259,7,515,Toan,Vietnam,Wonderful,9.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
260,7,134,Vân,Vietnam,Wonderful,9.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
261,7,673,Vu,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
262,7,268,Thu,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42
263,7,5541,Diệp,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-nghi-d...,NaN,NaN,NaN,NaN,9.42

In [8]:
dim_hotel = df2[[
    "hotel_id",
    "hotel_name",
    "hotel_location",
    "hotel_address",
    "hotel_description",
    "hotel_url"
]].drop_duplicates()

In [9]:
dim_hotel.to_parquet('data/dim_hotel.parquet')

In [10]:
dim_user = df2[[
    "user_id",
    "user",
    "country"
]].drop_duplicates()

In [11]:
dim_user.to_parquet('data/dim_user.parquet')

In [12]:
fact_review = df2[[
    "hotel_id",
    "user_id",
    "rating",
    "review"
]]

In [13]:
fact_review.to_parquet('data/fact_review.parquet')

In [28]:
df2.drop(columns='hotel_id', inplace=True)

In [29]:
df2.columns = df2.columns.str.lower()
df2 = df2.rename(columns={"hotelid": "hotel_id", "userid": "user_id"})

In [30]:
df2

,hotel_id,user_id,user,country,review,rating,hotel_url,hotel_location,hotel_name,hotel_description,hotel_address,hotel_avg_rating
0,2,3,Lê,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-2-phon...,Vung Tau,Căn hộ 2 Phòng ngủ Tháp Tam Thắng,Beachfront Location: Căn hộ 2 Phòng ngủ Tháp T...,"Lihi Homestay, 790900 Vung Tau, Vietnam",9.25
1,2,17,Bánh,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-2-phon...,Vung Tau,Căn hộ 2 Phòng ngủ Tháp Tam Thắng,Beachfront Location: Căn hộ 2 Phòng ngủ Tháp T...,"Lihi Homestay, 790900 Vung Tau, Vietnam",9.25
2,2,6,Kỳ,Vietnam,Ổn nếu biết cách khắc phục.,7.0,https://www.booking.com/hotel/vn/can-ho-2-phon...,Vung Tau,Căn hộ 2 Phòng ngủ Tháp Tam Thắng,Beachfront Location: Căn hộ 2 Phòng ngủ Tháp T...,"Lihi Homestay, 790900 Vung Tau, Vietnam",9.25
3,2,15,Ngọc,Vietnam,Exceptional,10.0,https://www.booking.com/hotel/vn/can-ho-2-phon...,Vung Tau,Căn hộ 2 Phòng ngủ Tháp Tam Thắng,Beachfront Location: Căn hộ 2 Phòng ngủ Tháp T...,"Lihi Homestay, 790900 Vung Tau, Vietnam",9.25
4,3,7,Công,Vietnam,Ok,9.0,https://www.booking.com/hotel/vn/khach-san-lam...,Hanoi,Lam Anh Hotel 8 Ngoại Giao Đoàn BT3-10,Comfortable Accommodations: Lam Anh Hotel 8 Ng...,"BT3-10, Khu biệt thự, khu đoàn ngoại giao, phư...",9.00
...,...,...,...,...,...,...,...,...,...,...,...,...
1474574,8165,216,Diego,Brazil,Very Good,8.0,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63
1474575,8165,333,Martina,Italy,Very Good,8.0,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63
1474576,8165,75577,Reynald,France,Very Good,8.0,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63
1474577,8165,131478,Ivarsson,Sweden,Very Good,8.0,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63
1474578,8165,986,Osvaldo,France,Very Good,8.0,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63

In [31]:
df2.to_parquet('data/data_merge.parquet')

In [15]:
avg_rating = df2[["hotel_id", "hotel_avg_rating"]].drop_duplicates()

In [8]:
df3 = pd.read_parquet('data/hotel_ratings.parquet')
df3

,hotel_id,user_id,user,country,review,rating
0,2,3,Lê,Vietnam,Exceptional,10.0
1,2,17,Bánh,Vietnam,Exceptional,10.0
2,2,6,Kỳ,Vietnam,Ổn nếu biết cách khắc phục.,7.0
3,2,15,Ngọc,Vietnam,Exceptional,10.0
4,3,7,Công,Vietnam,Ok,9.0
...,...,...,...,...,...,...
1474574,8165,216,Diego,Brazil,Very Good,8.0
1474575,8165,333,Martina,Italy,Very Good,8.0
1474576,8165,75577,Reynald,France,Very Good,8.0
1474577,8165,131478,Ivarsson,Sweden,Very Good,8.0
1474578,8165,986,Osvaldo,France,Very Good,8.0

In [19]:
df3.columns = df3.columns.str.lower()
df3 = df3.rename(columns={"hotelid": "hotel_id", "userid": "user_id"})

In [20]:
df3

,hotel_id,user_id,user,country,review,rating
0,2,3,Lê,Vietnam,Exceptional,10.0
1,2,17,Bánh,Vietnam,Exceptional,10.0
2,2,6,Kỳ,Vietnam,Ổn nếu biết cách khắc phục.,7.0
3,2,15,Ngọc,Vietnam,Exceptional,10.0
4,3,7,Công,Vietnam,Ok,9.0
...,...,...,...,...,...,...
1474574,8165,216,Diego,Brazil,Very Good,8.0
1474575,8165,333,Martina,Italy,Very Good,8.0
1474576,8165,75577,Reynald,France,Very Good,8.0
1474577,8165,131478,Ivarsson,Sweden,Very Good,8.0
1474578,8165,986,Osvaldo,France,Very Good,8.0

In [21]:
df3.to_parquet('data/hotel_ratings.parquet')

In [9]:
df4 = pd.read_parquet('data/hotel_details.parquet')
df4

,hotel_url,hotel_location,hotel_id,hotel_name,hotel_description,hotel_address,hotel_avg_rating
0,https://www.booking.com/hotel/vn/can-ho-2-phon...,Vung Tau,2,Căn hộ 2 Phòng ngủ Tháp Tam Thắng,Beachfront Location: Căn hộ 2 Phòng ngủ Tháp T...,"Lihi Homestay, 790900 Vung Tau, Vietnam",9.25
1,https://www.booking.com/hotel/vn/bn-center.htm...,Nha Trang,1,BN Boutique Nha Trang Beach,Prime Beachfront Location: BN Boutique Nha Tra...,"17 Nguyễn Thị Minh Khai 4, Nha Trang, Vietnam",8.03
2,https://www.booking.com/hotel/vn/khach-san-lam...,Hanoi,3,Lam Anh Hotel 8 Ngoại Giao Đoàn BT3-10,Comfortable Accommodations: Lam Anh Hotel 8 Ng...,"BT3-10, Khu biệt thự, khu đoàn ngoại giao, phư...",9.00
3,https://www.booking.com/hotel/vn/thang-linh-th...,Da Lat,4,Guesthouse Thắng Linh,Comfortable Accommodations: Guest house Thắng ...,"16/6 Nam Kỳ Khởi Nghĩa, Da Lat, Vietnam",8.54
4,https://www.booking.com/hotel/vn/villa-nga-hoa...,Da Lat,5,villa Nga Hoàng Đà lạt,Spacious Accommodations: Villa Nga Hoàng Đà lạ...,"07/4 Ngô Quyền, Da Lat, Vietnam",8.38
...,...,...,...,...,...,...,...
8160,https://www.booking.com/hotel/vn/swiss-belhote...,Danang,8161,Son Tra Beach Resort & Spa Danang,"This large resort in Danang, is located on the...","Bai Nam Bai Con Son Tra District, Danang, Vietnam",8.41
8161,https://www.booking.com/hotel/vn/starcity-stay...,Nha Trang,8163,Grand StarCity with Seaview,Beachfront Location: Grand StarCity with Seavi...,"Trần Phú, 57106 Nha Trang, Vietnam",10.00
8162,https://www.booking.com/hotel/vn/forest-tag-ho...,Hue,8162,Forest Tag Homestay,Comfortable Accommodations: Forest Tag Homesta...,"130 Trường Chinh, Hue, Vietnam",9.26
8163,https://www.booking.com/hotel/vn/ham-homestay-...,Vung Tau,8164,Ham Homestay,Comfortable Accommodations: Ham Homestay in Vu...,"163 Bà Triệu, Vung Tau, Vietnam",8.50
8164,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,8165,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63

In [16]:
df4 = df4.merge(avg_rating, on="hotel_id", how="left")

In [17]:
df4

,hotel_url,hotel_location,hotel_id,hotel_name,hotel_description,hotel_address,hotel_avg_rating
0,https://www.booking.com/hotel/vn/can-ho-2-phon...,Vung Tau,2,Căn hộ 2 Phòng ngủ Tháp Tam Thắng,Beachfront Location: Căn hộ 2 Phòng ngủ Tháp T...,"Lihi Homestay, 790900 Vung Tau, Vietnam",9.25
1,https://www.booking.com/hotel/vn/bn-center.htm...,Nha Trang,1,BN Boutique Nha Trang Beach,Prime Beachfront Location: BN Boutique Nha Tra...,"17 Nguyễn Thị Minh Khai 4, Nha Trang, Vietnam",8.03
2,https://www.booking.com/hotel/vn/khach-san-lam...,Hanoi,3,Lam Anh Hotel 8 Ngoại Giao Đoàn BT3-10,Comfortable Accommodations: Lam Anh Hotel 8 Ng...,"BT3-10, Khu biệt thự, khu đoàn ngoại giao, phư...",9.00
3,https://www.booking.com/hotel/vn/thang-linh-th...,Da Lat,4,Guesthouse Thắng Linh,Comfortable Accommodations: Guest house Thắng ...,"16/6 Nam Kỳ Khởi Nghĩa, Da Lat, Vietnam",8.54
4,https://www.booking.com/hotel/vn/villa-nga-hoa...,Da Lat,5,villa Nga Hoàng Đà lạt,Spacious Accommodations: Villa Nga Hoàng Đà lạ...,"07/4 Ngô Quyền, Da Lat, Vietnam",8.38
...,...,...,...,...,...,...,...
8160,https://www.booking.com/hotel/vn/swiss-belhote...,Danang,8161,Son Tra Beach Resort & Spa Danang,"This large resort in Danang, is located on the...","Bai Nam Bai Con Son Tra District, Danang, Vietnam",8.41
8161,https://www.booking.com/hotel/vn/starcity-stay...,Nha Trang,8163,Grand StarCity with Seaview,Beachfront Location: Grand StarCity with Seavi...,"Trần Phú, 57106 Nha Trang, Vietnam",10.00
8162,https://www.booking.com/hotel/vn/forest-tag-ho...,Hue,8162,Forest Tag Homestay,Comfortable Accommodations: Forest Tag Homesta...,"130 Trường Chinh, Hue, Vietnam",9.26
8163,https://www.booking.com/hotel/vn/ham-homestay-...,Vung Tau,8164,Ham Homestay,Comfortable Accommodations: Ham Homestay in Vu...,"163 Bà Triệu, Vung Tau, Vietnam",8.50
8164,https://www.booking.com/hotel/vn/qua-cam-tim-h...,Hoi An,8165,Qua Cam Tim Homestay,Comfortable Accommodations: Qua Cam Tim Homest...,"92 Nguyen Phuc Tan Street, Cam Pho Ward, Minh ...",9.63

In [18]:
df4.to_parquet('data/hotel_details.parquet')